name: hayvanlar
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.14.2
  flip_card: ^0.5.0
  sprintf: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
      - assets/
      - images/
  fonts:
     - family: Merienda
       fonts:
         - asset: fonts/Merienda-Regular.ttf
